server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  security:
    jwt:
      key: "averyverylongkey"
      expire: 10
    filter:
      order: -100

  r2dbc:
    url: r2dbc:mysql://localhost:3306/test?sslMode=DISABLED&serverTimezone=UTC
    username: root
    password: 123456

  r2dbc.pool:
    enabled: true
    max-size: 20
    initial-size: 10
    validation-query: SELECT 1

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com:
      example:
        warehouse:
          controller: debug
          service: debug
          interceptor: debug
          filter: debug

  file:
    name: logs/warehouse.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
